### ISSUE TITLE
operating with int. and str.

### ISSUE THREAD

**Issue by phonicdev** [mattlaguardia/py-timer#1]
Hey, bit of an issue, that it doesnt work.

perhaps this is because this is python 2? not sure.

but here:
         Number of Seconds: 4
Traceback (most recent call last):
  File "/home/rob/Documents/timer.py", line 7, in <module>
    finishTime = startTime + seconds
TypeError: unsupported operand type(s) for +: 'float' and 'str'

**Comment by mattlaguardia** [comment]
This timer was written in python 2.7 - I have not spent too much time on version 3 and would guess that it is throwing an error because its a newer version and does not have the same built-in methods. This code is still working for me.
